### ISSUE TITLE
Create dunfell branch

### ISSUE THREAD

**Issue by FinitelyFailed** [Azure/meta-azure-device-update#3]
Hi,

I have forked this repo and created a dunfell branch, and made it work. Now I would like to create a pull request from my fork into this repo. However I can't do that if there are no dunfell branch to target. So can you please create one?

Best regards

**Comment by volzer-lincoln** [comment]
@FinitelyFailed, I'm looking to leverage this layer on dunfell as well - would you be willing to share your fork since your request to get a dunfell branch created seems to be stuck?

**Comment by FinitelyFailed** [comment]
@volzer-lincoln, here you go, you will need both of these:
- https://github.com/GaiaSystem/meta-azure-device-update/tree/dunfell
- https://github.com/GaiaSystem/meta-iot-hub-device-update-delta/tree/dunfell

Note that I didn't do much to get it working on dunfell.

**Comment by Nox-MSFT** [comment]
Note: [dunfell](https://github.com/Azure/meta-azure-device-update/tree/dunfell) branch is available now. But we haven't ported the code and test it.

@FinitelyFailed  please feel free to create the merge PR is you still need it.

Thank you.
