### ISSUE TITLE
Build for kirkstone fails

### ISSUE THREAD

**Issue by libreo-mwebert** [Azure/meta-azure-device-update#5]
When building this meta layer as a part of [iot hub device update](https://github.com/Azure/iot-hub-device-update-yocto/tree/user/jw-msft/kirkstone_tweaks), the build fails with:

cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/azure-device-update/1.0+gitAUTOINC+4794e82716-r0/image/usr/lib/adu/adu-shell': No such file or directory

When digging into the bb file, I think that the code here is not doing what the comment above tells us:
https://github.com/Azure/meta-azure-device-update/blob/kirkstone/recipes-azure-device-update/azure-device-update/azure-device-update_git.bb#L166
I am a newby with bitbake but I think that the adu directory is created but the adu-shell is not copied/installed? I fixed this with adding this line:

install -m 0550 ${D}${libdir}/../bin/adu-shell ${D}${libdir}/adu

For me, this fixed the build. Thoughts?

**Comment by Nox-MSFT** [comment]
@libreo-mwebert thanks for reporting the issue and suggesting the fix. We will take a look at it.
At a glance, the adu-shell file permission will need the 'setuid' (s) bit. So, please try this:

install -m **4**550 ${D}${libdir}/../bin/adu-shell ${D}${libdir}/adu

**Comment by Nox-MSFT** [comment]
Close this issue as we've recently made the [kirkstone](https://github.com/Azure/meta-azure-device-update/tree/kirkstone) branch available.
